### PR TITLE
Added ability to provide custom axios instance used by react-sanctum

### PR DESCRIPTION
**Pull request by pharmarin**

### CODE REVIEW

**Comment by koole** [comment]
Thanks for new feature! The code looks good, but I still have to test if it would not break any existing code.

I can't approve this pull request though, as it now contains many more changes, other than the custom axios instance option.

**Comment by sangeet** [comment]
I wish this PR would have been merged. I need to intercept requests and add a custom header to each request such as this :

```js
axios.interceptors.request.use(async (request) => {
    try {
        const csrf = Cookies.get('XSRF-TOKEN');
        request.withCredentials = true;

        if (csrf) {
            request.headers.common['XSRF-TOKEN'] = csrf;
        }

        return request;
    } catch (err) {
        throw new Error(`axios# Problem with request during pre-flight phase: ${err}.`);
    }
});
```
Any way to do this currently or will I have to basically create my own fork and add a custom instance?
For a library that works for authentication, some amount of extensibility is needed I feel.

**Comment by koole** [comment]
@sangeet I completely understand why you want to use a custom axios instance. I’ll gladly merge a pull request with this functionality!

The reason this pull request was closed is because it also contains other changes, like changing the name of the author and making changes to the build process.

If you could make a new pull requests which just adds this feature, I’ll merge it and release a new version of the package 👍

**Comment by koole** [comment]
@sangeet Nevermind that, I've released a new version of the package (2.0.1) which adds this functionality!

**Pull request closed without merging**
